The masked priming paradigm stands as a cornerstone in psycholinguistic investigations, providing critical insights into the mechanisms of word recognition. However, there is still uncertainty about whether lexical frequency interacts with masked repetition priming, a phenomenon known as the Frequency Attenuation Effect (FAE). Many early findings suggested no such interaction, but more recent studies have contradicted this view (see @tbl-litReview). Resolving this issue is theoretically important, as different word recognition models make divergent predictions about whether the FAE should occur in masked priming, and, if it does, how it should be explained.

## Accounting for the FAE

On one side, *interactive activation* (IA) models [@McClellandRumelhart1981; @GraingerJacobs1996; @ColtheartEtal2001] and *retrospective models* of priming, such as the *memory recruitment model* [@BodnerMasson1997; @MassonBodner2003; @Bodner2014], predict the FAE in masked priming. However, these theories differ in where they locate the effect. *IA* models predict a lexical origin [see @GraingerEtal2012], while the memory recruitment model suggests a post-lexical source.

On the other side, *search models*, such as the *entry-opening model* [@ForsterDavis1984], propose a more complex interaction between lexical and episodic memory. These models posit that under unmasked conditions, repetition priming is driven largely by *episodic* memory, but under masked priming, *episodic* memory plays no role, and thus masked repetition priming reveals primarily *lexical* (and perhaps also *sublexical*) level processes. According to the *entry-opening model*, only two processes are at play within lexical structure: a frequency-ordered lexical search and the time required to open an entry once a potential match is flagged (the *entry opening time*, EOT). The search is sensitive to word frequency, but the EOT is assumed to be uniform across all entries [and it is estimated at roughly 60ms by @ForsterEtal2003]. Consequently, the model predicts no interaction between frequency and repetition priming under masked conditions, meaning the FAE should not be observable in masked repetition priming.

Clearly then, the FAE in experiments 1 and 2 empirically aligns with the predictions of *IA* and *memory recruitment* models, insofar as both models predict an FAE under masked conditions. These findings contradict the *entry opening model*, which predict predict no FAE in masked repetition priming. However, further considerations suggest that the FAEs observed in our studies may be less supportive of the *memory recruitment model*, which predicts the FAE only when the context of the behavioral task justifies drawing on a non-lexical memory resources post-lexically, such as increased task difficulty. In our experiments, task difficulty was deliberately minimized: both words and non-words had very high accuracy rates in the English Lexicon Project, leading to item error rates that never rose above 14%, entirely avoiding the need for item exclusions. In addition, only 58 in 5200 participants, or 1.1%, had an overall error rate above 30%. Finally, many researchers may find implausible the assumption that episodic memory resources are formed at the very short prime duration used in experiment 1 (33 ms). Conversely, the *entry-opening model* predicts a null FAE because it assumes a fixed EOT. This assumption, based on the observation that the magnitude of masked repetition effects mirror prime duration up to 60 ms [@ForsterEtal2003], is contradicted by our findings. In Experiment 2, where the prime duration was 50 ms, the maximum repetition priming effect was 35 ms for low-frequency words, suggesting that EOTs are not fixed at 60 ms, nor do they match the prime duration in general [see @Wu2012 for a similar argument]. Moreover, repetition priming effects were consistently smaller for high-frequency words, further challenging the model's assumption of uniform EOTs. Thus, if we relax the assumption that EOTs are uniform across the lexicon and instead posit that lower-frequency words have longer entry opening times than higher-frequency words, the *entry-opening model*, like *IA* models, could account for the FAE.

## The independence of FAE from prime duration

What about the finding that the FAE does not seem to interact with prime duration? Here, these models seem to make the wrong predictions. *IA* models assume that it is stimulus exposure that drives activation of lexical nodes, and that frequency is directly related with lexical nodes activation levels, either in terms of setting their resting levels or in how fast they accumulate information from the input. @GraingerEtal2012 explains how the FAE is predicted by such a model: low-frequency words accumulate evidence more slowly that do high-frequency words. If one posits that stimulus repetition provide a uniform boost to lexical nodes, then compared to a situation where lexical nodes are at their resting activation levels (the unrelated condition), lower-frequency repeated words will reach their recognition threshold comparatively faster than would repeated high-frequency words [cf. @GraingerEtal2012, Fig. 1]. Under this view, however, the amount of activation boost to lexical nodes in the related condition is a function of stimulus exposure, and thus a longer prime duration should deliver a stronger initial activation boost, which can only lead to a magnification of the FAE. Therefore, it seems that the basic mechanics of *IA* models, together with the assumptions that allow them to capture the FAE, also predict an interactive effect between FAE magnitude and prime duration, with larger FAE magnitudes predicted when prime durations are longer. In experiments 1 and 2, however, the increase from a 33ms to a 50ms prime duration elicited FAEs of same magnitude (approximately 10ms).

The original *entry opening model* does not predict a FAE, and so it cannot make any predictions about its potential interaction with prime duration. However, the modified version of the *entry opening model* sketched above would be able to. If it is indeed true that EOTs are larger for lower-frequency words, then the relationship between prime duration and FAE should be somewhat non-linear: while prime duration equals the EOTs of the higher frequency words, then no FAE should be observed. While the prime duration exceeds the EOTs for the higher frequency words, but it is still shorter than the EOTs of the lower frequency words, the FAE should increase linearly with prime duration. It should reach its maximum when the prime duration equals the EOTs of the lower frequency words. Beyond that point, increases in prime duration should no longer lead to increases in FAE, which should remain at its maximum magnitude, namely the difference between the EOTs of high- and low-frequency words.

Unfortunately, we do not observe this predicted pattern in experiments 1 and 2. For instance, in Experiment 1, the repetition effect for low-frequency words is close to the prime duration (a 28ms effect for a 33ms prime duration), while the repetition effect for high-frequency words is 10ms shorter (a 18ms effect for a 33ms prime duration). If we assume that 28ms is not significantly different from 33ms, the modified *entry opening model* would predict that the prime duration has not yet exceeded the *opening times* of the low frequency words, while it clearly has exceeded the *opening times* of the high-frequency words. Thus, the model would predict that an increase in prime duration would also increase the magnitude of the repetition effect for the LF condition, but not for the HF condition, leading to a larger FAE. However, while we did observe an increase in the magnitude of the repetition effect for the LF condition in experiment 2 (28ms in Exp.1 and 35ms in Exp.2), the same was true for the HF condition (18ms in Exp.1 and 26ms in Exp.2), and thus the FAE was identical in magnitude across experiments. Conversely, if we take the results of experiment 1 at face value, and assume that the 33ms prime duration exceeds both the *opening times* of high- and low-frequency words (18ms and 28ms respectively), then the modified *entry opening model* would indeed make the prediction that the FAE observed in experiment 1 reveals the maximum of the FAE as 10ms, and that this value should not increase when prime duration increases. However, the same model would also make the prediction that the repetition priming effects should remain stable across experiments, contrary to fact (they are both approximately 8ms longer in experiment 2).

Thus, it seems neither *IA* models nor the modified *entry opening model* make the correct predictions about the pattern of results observed in experiments 1 and 2, namely a stable FAE effect across increases in prime duration, with a concomitant increase in repetition priming effects as a function of prime duration. *IA* models would have predicted an increased FAE in experiment 2, and the modified *entry opening model* would have predicted either an increased FAE in experiment 2, or exactly identical results in terms of FAE and repetition priming effects magnitudes in experiments 1 and 2. 

Can these models be amended to allow them to capture the results? On the one hand, given their core mechanics, *IA* models can capture either a situation where FAE does not arise (ie. frequency is purely additive to repetition effects), or a situation where FAE is generated and its magnitude is necessarily a function of the prime duration. Neither of these patterns match the results of experiments 1 and 2. So the results of experiment 1 and 2 pose a real challenge for *IA* models.

On the other hand, a different modification to the original *entry opening model* may help explain both the existence of the FAE and its non-interaction with prime duration. If we assume that the exposure to the prime raises the rank order of the target word to the top of the search list, this would result in a boost that is a simple function of the repeated presentation, and therefore should not interact with prime duration. This boost would also impact high- and low-frequency words differently: while both words would benefit from repetition by being raised to the top of the search list, low-frequency words would be retrieved comparatively faster than high-frequency words when contrasted with their first retrieval times during the presentation of the prime. This simple mechanism explains at once the existence of the FAE and the fact that it does not interact with prime duration. For instance, in experiment 1, the 10ms FAE can be explained as follows: as the EOT is uniform, then it must be around 18ms (the repetition priming effect of high-frequency words). The repetition priming effect for low-frequency words (28ms) is then the the summation of the EOT (18ms) and the comparative speed up difference in retrieval time for the target words across high- and low-frequency condition (i.e, the FAE, which with this set of materials is 10ms). Unfortunately, this logic would fail to account for the results of experiment 2: if the EOT is indeed 18ms as shown in experiment 1, and the EOT is the only source of priming for high-frequency words, then this effect is already maxed out with a prime duration of 33ms. Why is it then that increasing the prime duration to 50ms in experiment 2 makes the effect approximately 8ms longer (26ms)? The only way this could be true is if the EOTs can vary substantially across samples of individuals; for instance, if the EOT for the sample in experiment 1 was 18ms, but it was 26ms for the sample in experiment 2. The problem with this assumption is that it seems arbitrary to assume that the EOT can vary substantially (here ~8ms) across our two very large samples, which are able to produce very narrow margins of errors around precise estimates for a number of relevant measurements, such as the mean and standard deviations RT for the unrelated conditions and non-word conditions and the magnitude of the FAE. Nonetheless, it may be a fruitful avenue for future studies to explore.

# Conclusion

Our study successfully replicated and expanded upon the work of @Angele2023, @Cayado2023 and @PetrosinoEtal2023, confirming the viability of observing repetition priming effects in masked priming experiments conducted online with both a short (33ms) and longer (50ms) priming durations. Notably, we were able to successfully address a lingering empirical question in the literature by establishing that the Frequency Attenuation Effect (FAE) does arises under masked conditions. We were able to determine additionally that the FAE is also independent of the duration of the prime. We contend that, while this pattern of results presents a direct challenge to both *IA* and *entry opening* models, the latter offers a few promising avenues for small modifications might enable it to accommodate the results of our studies. The most promising is the assumption that after the encounter with the prime, its entry is temporarily raised to the top of the rank frequency ordered search list. This modification explains at once the existence of the FAE, and its independence of the prime duration.
