---
title: "Script B: Experiment 1"
format: html

execute:
  include: false

---

## Libraries

```{r libraries}
#| echo: false
#| warning: false
#| error: false
#| message: false
library(osfr)
library(tidyverse)
library(knitr)
library(gt)
library(gtExtras)
library(rstatix)
library(ggpubr)
library(here)
```

## Materials

```{r}
#| warning: false
#| error: false
#| label: tbl-words_pilot
#| tbl-cap: "Pilot experiment. Descriptive statistics of the word item used. For both frequency databases, the word frequencies were converted to per-million count to ensure cross-comparison."

pilot_wordlists_folder <- "../materials/experiment1/"

stimuli <- read.csv(paste0(pilot_wordlists_folder, "frequency-effects_experiment1_stimuli.csv"))
database <- read.csv(paste0(pilot_wordlists_folder, "stim-database.csv"))

stimuli <- merge(stimuli, database, by='Word', all.x=T, all.y=F)
stimuli <- stimuli[c(-559,-596),] #one word and one non-word were duplicated as being considered both non-words and words

words <- stimuli %>% filter(type != 'non-word') 
nonwords <- stimuli %>% filter(type == 'non-word')

words$freq.bin <- factor(words$freq.bin, levels = c("high", "mid"))
words$type <- as.factor(words$type)

words %>% 
  filter(freq.bin != 'low') %>%
  mutate(Freq_HAL.Pm = (Freq_HAL * (10^6) / (131*10^6))) %>% # CHECK IF THE TRANSFORM HERE IS CORRECT
  mutate(freq.bin = fct_recode(freq.bin, low = "mid")) %>% 
  dplyr::group_by(freq.bin) %>%
  dplyr::summarise(N = n(),
            minFreq= min(Freq_HAL.Pm, na.rm = T), maxFreq=max(Freq_HAL.Pm, na.rm = T),
            meanFreq = mean(Freq_HAL.Pm, na.rm = T), sdFreq = sd(Freq_HAL.Pm, na.rm = T),
            minSUBFreq= min(SUBTLWF, na.rm = T), maxSUBFreq=max(SUBTLWF, na.rm = T),
            meanSUBFreq = mean(SUBTLWF, na.rm = T), sdSUBFreq = sd(SUBTLWF, na.rm = T),
            #meanRT=mean(as.numeric(I_Mean_RT), na.rm = T), sdRT=sd(as.numeric(I_Mean_RT), na.rm = T),
            #meanLength = mean(Length, na.rm = T), sdLength=sd(Length, na.rm = T)
            ) %>% 
  mutate(
    across(-freq.bin, ~ if_else(.<1, round(., 2), round(.)))
  ) %>% 
  gt() %>%
  tab_spanner(
    label = md("**HAL**"), 
    columns = c(minFreq: sdFreq)
  ) %>%
  tab_spanner(
    label = md("**SUBTLEX~US~**"), 
    columns = c(minSUBFreq: sdSUBFreq)
  ) %>%
  cols_label(freq.bin = "frequency", 
             minFreq = "min", maxFreq = "max", meanFreq = "mean", sdFreq = "SD", 
             minSUBFreq = "min", maxSUBFreq = "max", meanSUBFreq = "mean", sdSUBFreq = "SD") %>%
  gt_add_divider(columns=c("maxFreq", "maxSUBFreq"), weight=px(1))
  
```

## Data analysis

```{r}
#| label: pilot_raw-dataset
#| warning: false
#| error: false

# load the raw data dataframe
pilot_data_folder <- "experiment1"
pilot_rawdata_filename <- "experiment_1_preprocessed_data.csv"

## 02. check if the rawdata file exists. if not, download it from OSF.
if (!file.exists(here(pilot_data_folder, pilot_rawdata_filename))) {
  osf_retrieve_file("ej8dh") |> 
    osf_download(path = here(pilot_data_folder),
                 conflicts = "overwrite") 
}

## 03. read the data into R.
pilot_rawdata <- here(pilot_data_folder, pilot_rawdata_filename) |>
  read.csv(na = c("", "NA")) %>%
  filter(condition_rec != 'low') %>% # deleting the low-low frequency bin
  mutate(condition_rec = fct_recode(condition_rec, low = "mid"), # renaming the mid-frequency bin as low
         primeTime = primeDuration - maskDuration) # calculating the actual SOA

pilot_info <- list()
pilot_info$intended_prime_duration <- 33
pilot_info$prime_dur_lb <- 25
pilot_info$prime_dur_ub <- 60
pilot_info$rt_lb <- 200
pilot_info$rt_ub <- 1800
pilot_info$freq_conditions <- c("high", "low", "non-word")
pilot_info$n_recruited <- pilot_rawdata$Rec_Session_Id |>
  unique() |>
  length()

pilot_rawdata.sub <- pilot_rawdata %>%
  filter(!is.na(TimeMeasure_Mean) & !is.na(primeDuration) & !is.na(responseError))
            

pilot_info$summary <- with(
  transform(pilot_rawdata.sub,
    RT_inrange = ifelse(RT >= pilot_info$rt_lb & RT <= pilot_info$rt_ub, 1, 0),
    Prime_inrange = ifelse((primeDuration - maskDuration) >= pilot_info$prime_dur_lb &
                             (primeDuration - maskDuration) <= pilot_info$prime_dur_ub, 1, 0),
    list = Group_Nr),
  {
    data.frame(aggregate(Start_Time ~ Rec_Session_Id + Crowdsourcing_SubjId, data=pilot_rawdata.sub, unique),
               aggregate(End_Time_Local ~ Rec_Session_Id + Crowdsourcing_SubjId, data=pilot_rawdata.sub, unique),
              aggregate(cbind(list, SelectedGender, SelectedAge, TimeMeasure_Mean, TimeMeasure_Std) ~ Rec_Session_Id + Crowdsourcing_SubjId, data=pilot_rawdata.sub, unique),
      aggregate(cbind(responseError, RT_inrange, Prime_inrange) ~ Rec_Session_Id + Crowdsourcing_SubjId, mean, data=pilot_rawdata.sub)
  )
}
)

pilot_info$summary <- pilot_info$summary[, -grep("Rec_Session_Id.|Crowdsourcing_SubjId.", colnames(pilot_info$summary))] # remove all extra aggregating columns (subj ID)

pilot_info$summary$Duration <- interval(ymd_hms(pilot_info$summary$Start_Time), 
                                             ymd_hms(pilot_info$summary$End_Time_Local)) |>
                                      lapply(function(interval_value) {interval_value/dminutes(1)}) |> 
                                           unlist()

```

### Step 1: subject and item performance 

```{r}
#| label: pilot_performance
#| message: false
#| error: false
#| warning: false

pilot_step1_goodsubj <- pilot_info$summary |>
  subset(responseError <= .3) 

pilot_step1_subj_remain <- pilot_step1_goodsubj |> nrow()

pilot_step1_item.err <- pilot_rawdata.sub %>% group_by(condition_rec, target_rec) %>%
  summarise(word.percent=mean(responseError)*100) %>% 
  filter(word.percent > 30)

pilot_subj_filter_1 <- pilot_step1_goodsubj$Rec_Session_Id
pilot_item_filter_1 <- pilot_step1_item.err$target_rec

pilot_data_step1 <- pilot_rawdata.sub |>
  subset(condition_rec %in% pilot_info$freq_conditions) |>
  subset(Rec_Session_Id %in% pilot_subj_filter_1 & 
         !target_rec %in% pilot_item_filter_1)
```

### Step 2: prime durations

```{r}
#| label: pilot_prime-durations
#| message: false
#| warning: false
#| error: false
  
pilot_summary.primeTime <- pilot_rawdata.sub %>% 
  summarise(meanPrimeTime = round(mean(primeTime), 2), 
            sdPrimeTime = round(sd(primeTime), 2))

pilot_primeTimeRangeSummary <- pilot_rawdata.sub %>% 
  group_by(primeTime) %>%
  mutate(range = ifelse(primeTime < pilot_info$prime_dur_lb, "below", 
                        ifelse(primeTime > pilot_info$prime_dur_ub, "above",
                               "in range"))) %>% 
  group_by(range) %>% tally() %>% ungroup() %>%
  mutate(range.percent = round((n*100)/nrow(pilot_rawdata.sub),2))

pilot_data_step2 <- pilot_data_step1  |>
  subset(primeTime >= pilot_info$prime_dur_lb & primeTime <= pilot_info$prime_dur_ub)

pilot_step2_subj_remain <- pilot_data_step2$Rec_Session_Id |>
  unique() |>
  length()

pilot_step2_trials_remain <- nrow(pilot_data_step2)

```

### Step 3: RT analysis

```{r}
#| label: pilot_RT-outliers
#| message: false
#| error: false
#| warning: false

# RT outliers 
pilot_data_step3 <- pilot_data_step2 |> 
  subset(RT >= pilot_info$rt_lb & RT <= pilot_info$rt_ub)

pilot_step3_subj_remain <- pilot_data_step3$Rec_Session_Id |>
  unique() |>
  length()

pilot_step3_trials_remain <- nrow(pilot_data_step3)

# error trial removal

pilot_data_step3b <- pilot_data_step3  |>
  subset(responseError == 0)

pilot_step3b_subj_remain <- pilot_data_step3b$Rec_Session_Id |>
  unique() |>
  length()

pilot_step3b_trials_remain <- nrow(pilot_data_step3b)

# remove subjects with less than 12 trials in at least one condition*primetype combination (half of the total number of items per combination)
rt_data_labels <- c("Rec_Session_Id", "condition_rec", "primetype_rec", "RT")

pilot_subj_filter_2 <- pilot_data_step3b[, rt_data_labels] |>
  aggregate(RT ~ ., FUN = length, drop = FALSE) |>
  subset(RT < 12, select = Rec_Session_Id) |>
  unique() |>
  unlist()

pilot_data_final <- pilot_data_step3b |>
  subset(!(Rec_Session_Id %in% pilot_subj_filter_2))

pilot_final_subj_remain <- pilot_data_final$Rec_Session_Id |>
  unique() |> 
  length()
  
pilot_final_trials_remain <- nrow(pilot_data_final)

```

## Results

```{r}
#| label: pilot_results
#| message: false
#| error: false
#| warning: false

# error rates averages
### N.B.: to calculate error rates, will have to apply the 12-trial removal procedure after the RT removal procedure and without removing the error trials
pilot_subj_filter_2_with.errors <- pilot_data_step3[, rt_data_labels] |> #pilot_data_step3 is the dataset after RT removal and before the error trial removal
  aggregate(RT ~ ., FUN = length, drop = FALSE) |>
  subset(RT < 12, select = Rec_Session_Id) |>
  unique() |>
  unlist()

pilot_data_final_with.errors <- pilot_data_step3 |>
  subset(!(Rec_Session_Id %in% pilot_subj_filter_2))

pilot_error.rates <- pilot_data_final_with.errors %>%
  mutate(primetype_rec = factor(primetype_rec, levels=c("unrelated", "related")),
         condition_rec = factor(condition_rec, levels=c("high", "low", "non-word"))) %>%
  group_by(condition_rec, primetype_rec, Rec_Session_Id) %>%
  summarise(error.percent=mean(responseError)*100)

# RT averages
pilot_rt.avg_subj <- pilot_data_final %>% 
  group_by(Rec_Session_Id, condition_rec, primetype_rec) %>%
  summarise(meanRT = mean(RT))

pilot_rt_cor <- pilot_data_final %>% 
  group_by(Rec_Session_Id, condition_rec, primetype_rec) %>%
  dplyr::summarise(meanRT=mean(RT)) %>%
  select(Rec_Session_Id, condition_rec, primetype_rec, meanRT) %>% 
  pivot_wider(names_from='primetype_rec', values_from=c('meanRT')) %>%
  group_by(condition_rec) %>%
  summarise(cor=cor(unrelated, related))

# RT + error averages (by subject)
pilot_avgs_subj <- merge(pilot_rt.avg_subj, pilot_error.rates, by=c("Rec_Session_Id", "condition_rec", "primetype_rec"))

pilot_mop.err_across <- pilot_avgs_subj %>%
  group_by(condition_rec, primetype_rec) %>%
  summarise(gd.mean=mean(meanRT, na.rm=T), sd=sd(meanRT, na.rm=T), mean.error=mean(error.percent)) %>%
  pivot_wider(id_cols="condition_rec", names_from=primetype_rec, values_from=c(gd.mean, sd, mean.error)) %>%
  left_join(pilot_rt_cor, by="condition_rec")

#### ERROR PRIMING CALCULATIONS ####
# we will just run stats for this, no numerical calculations (e.g., priming)

### MAIN EFFECTS
#### t-test
pilot_errors_stats_main <- pilot_error.rates %>% 
  group_by(condition_rec) %>%
  t_test(error.percent ~ primetype_rec, paired=T)

#### RT PRIMING CALCULATIONS ####

### 2x2 ANOVA
pilot_mop_anova <- pilot_rt.avg_subj |>
  transform(Rec_Session_Id = factor(Rec_Session_Id)) |>
  subset(condition_rec %in% c("high", "low")) |>
  aov(meanRT ~ condition_rec * primetype_rec + Error(Rec_Session_Id/(condition_rec * primetype_rec)), data = _)

### MAIN EFFECTS
#### by subject
pilot_mop_subj <- pilot_rt.avg_subj %>% 
  pivot_wider(names_from=primetype_rec, values_from=meanRT) %>%
  mutate(priming = unrelated-related)

#### descriptive stats
pilot_gdavg_mop <- pilot_mop_subj %>%
  group_by(condition_rec) %>%
  summarise(MOP = mean(priming), se = sd(priming)/sqrt(n()), ci=(qt(0.975, n()-1)*se),
            sd=sd(priming), ES=round(MOP/sd, 2))

#### summary table
pilot_gdavg_mop_summary <- pilot_gdavg_mop %>%
  left_join(., pilot_mop.err_across, by='condition_rec') %>%
  mutate(across(c(2:5, 7:12), round), across(c(13), round, 2)) %>%
  mutate(ci.lb = paste0("[", MOP-ci), ci.ub = paste0(MOP+ci, "]")) %>%
  unite("CI", ci.lb:ci.ub, sep = " ") %>% select(-ci, -se) %>% 
  rename(factor = "condition_rec") %>%
  relocate(gd.mean_related:cor, .before=MOP) %>% 
  relocate(gd.mean_related, .after=gd.mean_unrelated) %>%
  relocate(CI, .after=MOP)

#### t-test
pilot_rt_stats_main <- pilot_rt.avg_subj %>%
  mutate(primetype_rec = fct_relevel(primetype_rec, "unrelated", "related")) %>%
  group_by(condition_rec) %>%
  t_test(meanRT ~ primetype_rec, paired=T) %>% select(-2:-6) %>%
  rename(factor = "condition_rec", t='statistic') %>%
  mutate_if(is.numeric, list(~as.character(signif(., 3))))

### INTERACTION EFFECT
#### descriptive stats
pilot_gdavg_fae <- pilot_mop_subj %>%
  select(-unrelated, -related) %>%
  pivot_wider(names_from="condition_rec", values_from="priming") %>%
  mutate(interaction = low-high) %>% ungroup() %>%
  summarise(factor = "frequency:primetype", 
            sd=sd(interaction), se = sd/sqrt(n()), ci = (qt(0.975, n()-1)*se)) %>%
  mutate(across(c(2:4), round))

##### summary table
pilot_gdavg_fae_summary <- pilot_mop_subj %>% 
  select(-unrelated, -related) %>% ungroup() %>%
  pivot_wider(names_from="condition_rec", values_from="priming") %>%
  summarise(mean_high = round(mean(high)), mean_low = round(mean(low)), cor=round(cor(high, low), 3)) %>%
  bind_cols(., pilot_gdavg_fae) %>%
  mutate(MOP = mean_low-mean_high, ES = round(MOP/sd, 2), ci.lb = paste0("[", MOP-ci), ci.ub = paste0(MOP+ci, "]")) %>%
  unite("CI", ci.lb:ci.ub, sep = " ") %>% select(-ci, -se) %>% 
  relocate(CI, .after=MOP) %>%
  relocate(factor, .before=mean_high)
  
#### t-test
pilot_rt_stats_interaction <- pilot_mop_subj %>% ungroup() %>%
  filter(condition_rec != 'non-word') %>%
  mutate(condition_rec = fct_relevel(condition_rec, "low", "high")) %>%
  t_test(priming ~ condition_rec, paired=TRUE) %>% 
  mutate_if(is.numeric, list(~as.character(signif(., 3)))) %>%
  select(-1, -4:-5) %>%
  unite("factor", group1:group2) %>%
  rename(t='statistic') %>%
  mutate(factor = "frequency:primetype")
```

#### Stats summary

```{r}
#| message: false
#| error: false
#| warning: false
#| label: tbl-statsResults
#| tbl-cap: "Pilot experiment. Summary of the word priming results. *Legend.* MOP: magnitude of priming."
#| tbl-pos: 'h'

pilot_summary.results_mop <- merge(pilot_gdavg_mop_summary, pilot_rt_stats_main, by='factor')
pilot_summary.results_fae <- merge(pilot_gdavg_fae_summary, pilot_rt_stats_interaction, by='factor') |>
  select(-mean_high, -mean_low)

pilot_summary.results <- bind_rows(pilot_summary.results_mop, pilot_summary.results_fae)
  
pilot_summary.results %>%
  relocate(c("sd_unrelated", "mean.error_unrelated"), .before=gd.mean_related) %>%
  gt() %>%
  cols_label(
    CI = "95% CI",
    contains("mean") ~ "mean",
    contains("sd") ~ "SD", 
    contains("error") ~ "Error (%)"
  ) %>%
  tab_spanner(
    label = "unrelated RT",
    columns = c(2:4)
  ) %>%
  tab_spanner(
    label = "repetition RT",
    columns = c(5:7)
  ) %>%
  tab_spanner(
    label = 'priming effects',
    columns = c(9:12)
  ) %>%
  tab_spanner(
    label = md("_t_-test"),
    columns = c(13:15)
  ) %>%
  cols_label(
    sd = md("SD~p~")
  ) %>%
  cols_label(
    t = md("_t_"),
    p = md("_p_"),
  ) %>%
   sub_missing(
    missing_text = " "
  )
```
